version: '2.4'
services:
  rancher:
    image: rancher/rancher:latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.rancher.entrypoints=websecure"
    - "traefik.http.routers.rancher.rule=Host(`rancher.lukemilius.com`)"
    - "traefik.http.routers.rancher.middlewares=tfa_verify@file"
    - "traefik.http.routers.rancher.tls=true"
    - "traefik.docker.network=proxy"
    - "traefik.http.routers.rancher-internal.entrypoints=websecure"
    - "traefik.http.routers.rancher-internal.rule=Host(`rancher-int.lukemilius.com`)"
    - "traefik.http.routers.rancher-internal.middlewares=internal_only@file"
    - "traefik.http.routers.rancher-internal.tls=true"
    expose:
    - 80
    volumes:
    - data:/var/lib/rancher
    networks:
    - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  data:
