version: '2.4'
services:
  whoami:
    image: containous/whoami
    labels:
#    - "traefik.http.routers.whoami.entrypoints=web"
#    - "traefik.http.routers.whoami.rule=Host(`whoami.lukemilius.com`)"
#    - "traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https"
#    - "traefik.http.routers.whoami.middlewares=whoami-https-redirect"
    - "traefik.http.routers.whoami-secure.entrypoints=websecure"
    - "traefik.http.routers.whoami-secure.rule=Host(`whoami.lukemilius.com`)"
    - "traefik.http.routers.whoami-secure.tls=true"
    expose:
    - 80
    networks:
    - proxy
    scale: 2

networks:
  proxy:
    external: true
