version: '2.4'
services:
  whoami:
    image: containous/whoami
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.entrypoints=websecure"
    - "traefik.http.routers.whoami.rule=Host(`whoami.lukemilius.com`)"
    - "traefik.http.routers.whoami.middlewares=tfa-verify"
    - "traefik.http.routers.whoami.tls=true"
    expose:
    - 80
    networks:
    - proxy
    scale: 3
    restart: always

networks:
  proxy:
    external: true
