version: '2.4'
services:
  whoami:
    image: containous/whoami
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.entrypoints=websecure"
    - "traefik.http.routers.whoami.rule=Host(`whoami.lukemilius.com`)"
    - "traefik.http.routers.whoami.middlewares=tfa-verify"
    - "traefik.http.routers.whoami.tls=true"
    expose:
    - 80
    networks:
    - proxy
    scale: 3

  whoami2:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.entrypoints=websecure"
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.lukemilius.com`)"
      - "traefik.http.routers.whoami2.middlewares=github_auth@file"
      - "traefik.http.routers.whoami2.tls=true"
    expose:
      - 80
    networks:
      - proxy
    scale: 3

networks:
  proxy:
    external: true
