version: '2.4'
services:
  whoami:
    image: containous/whoami
    labels:
    - "traefik.http.routers.whoami.rule=Host(`whoami.lukemilius.com`)"
    - "traefik.http.routers.whoami.entrypoints=websecure"
    ports:
    - 80
    networks:
    - proxy
    scale: 2

networks:
  proxy:
    external: true
