version: '2.4'
services:
  volumerize:
    image: blacklabelops/volumerize:latest
    labels:
    - "traefik.enable=false"
    volumes:
    - portainer_portainer:/source/portainer_portainer:ro
    - proxy_letsencrypt:/source/proxy_letsencrypt:ro
    - drone_data:/source/drone_data:ro
    - dashboard_data:/source/dashboard_data:ro
    - dashboard_config:/source/dashboard_config:ro
    - organizr_config:/source/organizr_config:ro

    - cache:/volumerize-cache
    - /mnt/cont_data/backups:/backup
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      VOLUMERIZE_SOURCE: /source
      VOLUMERIZE_TARGET: file:///backup


volumes:
  cache:
  portainer_portainer:
    external: true
  proxy_letsencrypt:
    external: true
  drone_data:
    external: true
  dashboard_data:
    external: true
  dashboard_config:
    external: true
  organizr_config:
    external: true

