version: '2.4'
services:
  web:
    image: vabene1111/recipes
    restart: unless-stopped
    environment:
      SECRET_KEY: $SECRET_KEY
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: djangodb
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: djangodb
      TIMEZONE: America/Chicago
      FRACTION_PREF_DEFAULT: 1
    volumes:
    - staticfiles:/opt/recipes/staticfiles
    - media:/opt/recipes/mediafiles
    labels: # traefik example labels
    - "traefik.enable=true"
    - "traefik.http.routers.recipes.entrypoints=websecure"
    - "traefik.http.routers.recipes.rule=Host(`recipes.lukemilius.com`)"
    - "traefik.http.routers.recipes.middlewares=tfa_verify@file"
    - "traefik.http.routers.recipes.tls=true"
    - "traefik.docker.network=proxy"
    expose:
    - 8080
    depends_on:
    - db
    networks:
    - net
    - proxy

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: djangodb
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: djangodb
    networks:
    - net


networks:
  net:
  proxy:
    external: true

volumes:
  db:
  staticfiles:
  media:
