kind: pipeline
name: default

steps:
- name: Deploy container
  image: docker/compose
  commands:
  - docker-compose up -d -H tcp://10.10.200.99:2375
  volume:
  - /var/run/docker.sock:/var/run/docker.sock
