version: '3'
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.16
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - data:/config
      - /mnt/media/books:/books
      - calibre_db:/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.entrypoints=websecure"
      - "traefik.http.routers.calibre-web.rule=Host(`calibre-web.lukemilius.com`)"
      - "traefik.http.routers.calibre-web.middlewares=tfa_verify@file"
      - "traefik.http.routers.calibre-web.tls=true"
      - "traefik.http.routers.calibrewebint.entrypoints=websecure"
      - "traefik.http.routers.calibrewebint.rule=Host(`calibre-webint.lukemilius.com`)"
      - "traefik.http.routers.calibrewebint.middlewares=internal_only@file"
      - "traefik.http.routers.calibrewebint.tls=true"
      - "traefik.docker.network=proxy"
    expose:
      - 8083
    restart: unless-stopped
    networks:
    - proxy

  calibre:
    image: lscr.io/linuxserver/calibre:5.37.0
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=America/Chicago
      - PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - calibre_db:/config
    expose:
    - 8080
    - 8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.rule=Host(`calibre.lukemilius.com`)"
      - "traefik.http.routers.calibre.middlewares=internal_only@file"
      - "traefik.http.routers.calibre.tls=true"
      - "traefik.http.routers.calibre.service=calibre"
      - "traefik.http.services.calibre.loadbalancer.server.port=8080"
      - "traefik.http.routers.calibrewebserver.entrypoints=websecure"
      - "traefik.http.routers.calibrewebserver.rule=Host(`calibrewebserver.lukemilius.com`)"
      - "traefik.http.routers.calibrewebserver.middlewares=internal_only@file"
      - "traefik.http.routers.calibrewebserver.tls=true"
      - "traefik.http.routers.calibrewebserver.service=calibrewebserver"
      - "traefik.http.services.calibrewebserver.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    networks:
    - proxy
  
  kavita:
    image: kizaing/kavita:latest
    volumes:
    - config:/kavita/config
    - /mnt/media/books:/books
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.books.entrypoints=websecure"
      - "traefik.http.routers.books.rule=Host(`books.lukemilius.com`)"
      - "traefik.http.routers.books.middlewares=tfa_verify@file"
      - "traefik.http.routers.books.tls=true"
      - "traefik.http.routers.booksint.entrypoints=websecure"
      - "traefik.http.routers.booksint.rule=Host(`booksint.lukemilius.com`)"
      - "traefik.http.routers.booksint.middlewares=internal_only@file"
      - "traefik.http.routers.booksint.tls=true"
      - "traefik.docker.network=proxy"
    environment:
      TZ: America/Chicago
    networks:
    - proxy

networks:
  proxy:
    external: true

volumes:
  config:
  data:
  calibre_db: