version: "2"
services:
  muximux:
    image: linuxserver/muximux
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=America/Chicago
    volumes:
      - config:/config
    expose:
      - 80
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.muximux.entrypoints=websecure"
    - "traefik.http.routers.muximux.rule=Host(`mux.lukemilius.com`)"
    - "traefik.http.routers.muximux.middlewares=tfa-verify"
    - "traefik.http.routers.muximux.tls=true"
    restart: unless-stopped

volumes:
  config: