version: "2"
services:
  virtman:
    image: djaydev/docker-virt-manager
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=America/Chicago
    volumes:
      - config:/config:rw
      - /dev/urandom:/dev/urandom:ro
    expose:
      - 5800
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.virtman.entrypoints=websecure"
    - "traefik.http.routers.virtman.rule=Host(`virtman.lukemilius.com`)"
    - "traefik.http.routers.virtman.middlewares=tfa_verify@file"
    - "traefik.http.routers.virtman.tls=true"
    restart: unless-stopped
    networks:
    - proxy

volumes:
  config:

networks:
  proxy:
    external: true