version: '2.4'
services:

  tiddlywiki:
    image: elasticdog/tiddlywiki:5
    command: 
    - /tiddlywiki
    - --listen
    - host=0.0.0.0
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.tiddlywiki.entrypoints=websecure"
    - "traefik.http.routers.tiddlywiki.rule=Host(`wiki.lukemilius.com`)"
    - "traefik.http.routers.tiddlywiki.middlewares=tfa_verify@file"
    - "traefik.http.routers.tiddlywiki.tls=true"
    - "traefik.docker.network=proxy"
    restart: unless-stopped
    volumes:
    - data:/tiddlywiki
    expose:
    - 8080
    networks:
    - proxy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    networks:
    - wiki_net
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.wiki.entrypoints=websecure"
    - "traefik.http.routers.wiki.rule=Host(`wiki2.lukemilius.com`)"
    - "traefik.http.routers.wiki.middlewares=tfa_verify@file"
    - "traefik.http.routers.wiki.tls=true"
    - "traefik.docker.network=proxy"
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASS}
      DB_NAME: wiki
    restart: unless-stopped
    expose:
      - 3000
    networks:
    - proxy
    - wiki_net

  trilium:
    image: zadam/trilium:0.55-latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.notes.entrypoints=websecure"
    - "traefik.http.routers.notes.rule=Host(`notes.lukemilius.com`)"
    - "traefik.http.routers.notes.middlewares=tfa_verify@file"
    - "traefik.http.routers.notes.tls=true"
    - "traefik.http.routers.notes-int.entrypoints=websecure"
    - "traefik.http.routers.notes-int.rule=Host(`notesint.lukemilius.com`)"
    - "traefik.http.routers.notes-int.middlewares=internal_only@file"
    - "traefik.http.routers.notes-int.tls=true"
    - "traefik.docker.network=proxy"
    restart: unless-stopped
    volumes:
    - trilium-data:/home/node/trilium-data
    expose:
    - 8080
    networks:
    - proxy

volumes:
  db-data:
  data:
  trilium-data:

networks:
  proxy:
    external: true
  wiki_net:
