version: '2.4'

services:
  app:
    image: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.lukemilius.com`)"
      - "traefik.http.routers.nextcloud.middlewares=internal_only@file"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - db
    volumes:
      - config:/var/www/html
    networks:
      - proxy
      - nextcloud
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db

  db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - data:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud


networks:
  proxy:
    external: true
  nextcloud:

volumes:
  config:
  data: