version: '2.4'
services:
  watchtower:
    image: containrrr/watchtower
    labels:
    - "traefik.enable=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
