version: '2.4'
services:
  status:
    image: louislam/uptime-kuma:1
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.status.entrypoints=websecure"
    - "traefik.http.routers.status.rule=Host(`status.lukemilius.com`)"
    - "traefik.http.routers.status.middlewares=tfa_verify@file"
    - "traefik.http.routers.status.tls=true"
    expose:
    - 3001
    volumes:
    - data:/app/data
    networks:
    - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  data:
