version: '2.4'
services:
  portainer:
    image: portainer/portainer:latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.entrypoints=websecure"
    - "traefik.http.routers.portainer.rule=Host(`portainer.lukemilius.com`)"
    - "traefik.http.routers.portainer.middlewares=tfa-verify"
    - "traefik.http.routers.portainer.tls=true"
    expose:
    - 9000
    volumes:
    - portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - proxy

networks:
  proxy:
    external: true

volumes:
  portainer:
