version: '2.4'
services:
  portainer:
    image: portainer/portainer:latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.entrypoints=websecure"
    - "traefik.http.routers.portainer.rule=Host(`portainer.lukemilius.com`)"
    - "traefik.http.routers.portainer.middlewares=tfa-verify"
    - "traefik.http.routers.portainer.tls=true"
    - "traefik.tcp.services.port-internal-svc.loadbalancer.server.port=9000"
    - "traefik.tcp.routers.port-internal.entrypoints=internal"
    - "traefik.tcp.routers.port-internal.rule=HostSNI(`portainer-int.lukemilius.com`)"
    - "traefik.tcp.routers.port-internal.service=port-internal-svc"
    expose:
    - 9000
    volumes:
    - portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - proxy
    restart: always

networks:
  proxy:
    external: true

volumes:
  portainer:
