version: '2.4'
services:
  portainer:
    image: portainer/portainer:latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.entrypoints=websecure"
    - "traefik.http.routers.portainer.rule=Host(`portainer.lukemilius.com`)"
    - "traefik.http.routers.portainer.middlewares=tfa_verify@file"
    - "traefik.http.routers.portainer.tls=true"
    - "traefik.http.routers.port-internal.entrypoints=websecure"
    - "traefik.http.routers.port-internal.rule=Host(`portainer-int.lukemilius.com`)"
    - "traefik.http.routers.port-internal.middlewares=internal_only@file"
    - "traefik.http.routers.port-internal.tls=true"
    expose:
    - 9000
    volumes:
    - portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  portainer:
