version: '2.4'
services:

  server:
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: America/Chicago
      SERVERURL: wireguard.lukemilius.com
      SERVERPORT: 51820
      PEERS: liphone,slate,carbon,tablet,gateway
    ports:
      - 51820:51820/udp
    volumes:
      - config:/config
      - /lib/modules:/lib/modules

networks:
  proxy:
    external: true

volumes:
  config:
